---
name: Check patch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-9
            container-name: el9stream
          - name: centos-stream-10
            container-name: el10stream

    name: Build and test on ${{ matrix.name }}
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
      - name: Mark repository as safe
        run: git config --global --add safe.directory "$(pwd)"

      - name: checkout sources
        uses: ovirt/checkout-action@main
      
      - name: install dnf dependencies
        run: dnf install -y autoconf automake gettext-devel git systemd make rpm-build libtool python3-pip epel-release python-devel

      - name: install python dependencies
        run: pip install flake8 tools

      - name: autogen
        run: ./autogen.sh

      - name: configure
        run: ./configure

      - name: run distcheck
        run: make -j distcheck

      - name: Build RPM
        run: make -j rpm

      - name: Collect artifacts
        run: |
            mkdir -p exported-artifacts
            find tmp.repos -iname \*rpm -exec mv "{}" exported-artifacts/ \;
            mv ./*tar.gz exported-artifacts/

      - name: test install
        run: |
            yum --downloadonly install -y exported-artifacts/*noarch.rpm

      - name: Upload artifacts
        uses: ovirt/upload-rpms-action@main
        with:
          directory: exported-artifacts/
